### ISSUE TITLE
BUG: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Gravitary** [nodecg/nodecg-obs#1]
Hey there, I really enjoy nodecg, but I just cant initialize this package.
The error happens at OBSUtility (nodecg-utility-obs/index.js:32:28), where the namespace replicant is declared. Apparently I'm getting a null object from the following:
`const namespacesReplicant = nodecg.Replicant('_obs:namespaces', {
			schemaPath: buildSchemaPath('namespaces'),
			persistent: false
		});`

EDIT:
All packages have been installed successfully via npm and bower. Followed the README.MD tutorial.

**Comment by Lange** [comment]
Hi Martin!

What version of NodeCG are you running? nodecg-obs requires the beta of
NodeCG v0.9 (you can get it by checking out the dev-0.9 branch).

- Alex

**Comment by Gravitary** [comment]
Hey Alex!

Thanks for coming back to me. Looks like I couldn't read. Found your `NodeCG v0.9` in the README.
I'll try it with CG0.9 and report back.

**Comment by Gravitary** [comment]
Alright, that error is gone but I'm still getting an asynchronous error
`XXXXXXX\nodecg\bundles\gravitary\node_modules\nodecg-utility-obs\index.js:242
        async _transition(transitionName) {
              ^^^^^^^^^^^
SyntaxError: Unexpected identifier`

**Comment by Lange** [comment]
What version of Node.js are you running? nodecg-obs requires v7 or newer.

**Comment by Gravitary** [comment]
Alright, works like a charm. Downgraded node to 6.11 after the issues with CG0.8. I expected it to be some sort of nodeJS issue (as it usually is, otherwise you wouldn't release this code), but thank you for the help.

Would be good to have that in the readme, a bit more highlighted.

**Comment by Gravitary** [comment]
**SOLVED:**
Using CG0.9-Beta and NodeJS 8.1.2

**Comment by Lange** [comment]
I've added a "Requirements" section to the readme, should help avoid this confusion in the future: https://github.com/nodecg/nodecg-obs#requirements

**Comment by dcbartlett** [comment]
I'm getting this on the following:

NodeJS: 8.14.0
NodeCG: 1.3.0

Should i open a new bug with details?
